apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cron
  namespace: batch-jobs
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cleanup-batch
            image: cleanup-batch:2.0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: DB_HOST
              value: "192.168.232.128"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password