apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cron
  namespace: batch-jobs
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: aliyun-registry-cred
          containers:
          - name: cleanup-batch
            image: crpi-e2h2rfj3kunrwe5n.cn-hangzhou.personal.cr.aliyuncs.com/mike-docker-registry/spring-batch-cleanup-job:__SET_BY_DEPLOY__
            imagePullPolicy: Always
            env:
            - name: DB_HOST
              value: "192.168.232.128"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
